### ISSUE TITLE
Blank page after the theme installation

### ISSUE THREAD

**Issue by pranavek** [samanyougarg/hanuman#1]
Installed the theme using the Ruby gem method.

While running the Jekyll site on local using command `bundle exec jekyll serve`,  noticed a build warning. 

_Build Warning: Layout 'home' requested in index.md does not exist._

Preview on the browser is returning a blank page.

**Comment by samanyougarg** [comment]
Yes, that's because your site is using the home layout in index.md.
You need to change it to **default** and it will start working.

You'll also need to copy or create the default _config.yml file in this repository. Similarly, you'll need to have a navigation.yml and author.yml in your _data directory.

I will update the documentation.
